language: rust

sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

before_script:
  - pip install 'travis-cargo<0.2' --user
  # osx
  - if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
  # linux
  - if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
  - export RUST_BACKTRACE=1

script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench &&
    travis-cargo --only stable doc

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
